# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the content of the local app directory to the working directory
COPY . .

# Install additional dependencies using pip
RUN pip install --no-cache-dir Flask requests xmltodict

# Install additional system packages if needed
# RUN apt-get update && apt-get install -y <package-name>

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]
