version: '3'
services:
  flask-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - db
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.wrk
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: flask_app_db
      POSTGRES_USER: flask_app_user
      POSTGRES_PASSWORD: flask_app_password
    ports:
      - "5432:5432"
